Upgrade to v2.6.0 of the Packet Terraform Provider
pulumi/pulumi-packet pull request #41
Opened 2019-10-28 19:10 UTC by stack72

2019-10-28 19:15 UTC, jen20 requested changes

2019-10-28 19:15 UTC, jen20 commented on resources.go
> +			"packet_spot_market_request": {Tok: makeDataSource(mainMod, "getSpotmarketRequest")},
SpotMarket?

2019-10-28 19:19 UTC, stack72 commented on resources.go
> +			"packet_spot_market_request": {Tok: makeDataSource(mainMod, "getSpotmarketRequest")},
Fixed

2019-10-30 10:30 UTC, jen20 approved these changes

2019-11-01 11:40 UTC, merged